name: Build PROS CLI

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
        
    - name: Check Python install
      run: |
        which python3
        python3 --version
        which pip3
        pip3 --version
        
    - name: Install Requirements
      run: python -m pip install --upgrade pip && pip install -r requirements.txt && pip uninstall -y typing
      
    - name: Run Pyinstaller
      run: pyinstaller -y pros.spec
#     run: pyinstaller -y pros.spec
#     if: ${{ maxtrix.os == 'macos-latest' }}
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: dist/*
